#!/usr/bin/env node

// GRUNT-GITHOOKS START
var exec = require("child_process").exec;

exec("npm run lint", function (err, stdout, stderr) {
    console.log(stdout);

    var exitCode = 0;
    if (err) {
        console.error("Pre commit hook FAILED! JSHint failed or an error occurred.");
        console.log(stderr);
        exitCode = -1;
    }

    process.exit(exitCode);
});

// GRUNT-GITHOOKS END
